### ISSUE TITLE
What is 'a' in the mpv shader?

### ISSUE THREAD

**Issue by ianrrees** [lonetech/LookingGlass#3]
Hello,
    Obviously a question rather than an issue:  I've been slowly working towards an OpenGL program that drives the Looking Glass directly, and want to check my understanding of the 'a' parameter for quilt_map() in the mpv shader.  Is it effectively the azimuth angle, which the current pixel/texel is visible from?

I have interpreted it that way and got some weird looking results, but could have other issues too...  FWIW, the approach I'm taking is to render a scene in to 45 layers of an OpenGL texture array, then the fragment shader picks the relevant texture according to 'a'.

**Comment by lonetech** [comment]
It's really position across the lenslet. I have not attempted to measure more closely how that relates to output angle; it could be proportional to tangent, sine, angle, or simply not linear. These functions are frequently approximated using a radial second degree function, e.g. in Hugin/Panotools. With a span of plus or minus twenty degrees, there should be observable difference between the functions, but I don't know how significant.

**Comment by ianrrees** [comment]
Got it, thanks!  Am hoping to have some more time to work on this over the weekend.

**Comment by lonetech** [comment]
One oops: the `a` value is actually a count of lenslets crossed; we take the fractional part of it to get the position across the lenslet. That's within quilt_map(). Since we only care about the fractional part, it would also make sense to calculate in fixed point wrapping math.

**Comment by ianrrees** [comment]
Cool, I've got a "spinning cube" going, the issue was unrelated to the shader.  Will aim to clean up the code and share on github after work this evening.

I'm a total newbie with GPU programming, is there an advantage of using fixed point over `fract()`?  At this point, I'm using `fract(a) * 45` to pick a texture from a texture array.

**Comment by ianrrees** [comment]
Here's that spinning cube program - I intend to do a bit more tidy-up and add something static in the background so that the 3D-ness is more obvious.  https://github.com/ianrrees/lookingglass_cube
